### ISSUE TITLE
multi/exec transactions complete after client-side exceptions

### ISSUE THREAD

**Issue by yurymann** [aio-libs/aioredis-py#696] opened 2020-02-07 13:34 UTC
Way to reproduce:
1. Add a number of commands to a multi/exec pipeline, including one with a None argument. 
2. After calling execute(), aioredis throws `TypeError("args must not contain None")` for the None argument. 
3. The exception is recorded in the failed command's Future. But the rest of the commands are executed!
4. As the result, only a part of the multi/exec pipeline is executed. 

Expected behaviour: the whole transaction should be either executed completely or discarded completely. Current behaviour results in corrupted data and nasty logical errors in our application. 

I guess [this line](https://github.com/aio-libs/aioredis/blob/8a207609b7f8a33e74c7c8130d97186e78cc0052/aioredis/commands/transaction.py#L264) should be conditional on whether any command was processed with an exception.

**Comment by seandstewart** [comment] 2020-11-30 14:33
This is because we're scheduling all of the commands with Futures, so execution order isn't guaranteed. It's a tricky problem which will likely mean we need a new API to do properly.

Ideally we should build a buffer of commands and execute them synchronously, perhaps providing a `flush()` method to flush the buffer and send to the Redis server manually (See Redis-py's [Pipeline impl](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L4083)).

I'm guessing this implementation is also the cause of performance issues (#700), since we're making an untold number of network calls. Even though they're not blocking the client, they're blocking the server.

**Comment by seandstewart** [comment] 2021-03-18 23:40
Hey @yurymann -

I've just merged #891, which re-writes aioredis from the ground up as an asyncio port of redis-py. This means the Pipeline implementation should ensure we don't get into  the mixed-commit state you saw on an exception.

**Closed by seandstewart** 2021-03-18 23:40 UTC
Labels: bug, help wanted
