### ISSUE TITLE
Having issues with aioredis.from_url(<unix socket addr>)

### ISSUE THREAD

**Issue by a-pixel-on-your-screen** [aio-libs/aioredis-py#968] opened 2021-05-07 06:41 UTC
https://aioredis.readthedocs.io/en/latest/getting-started/#connecting
asyncio.from_url("unix:///run/redis.sock")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venv/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/venv/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 3, in main
  File "/root/venv/lib/python3.9/site-packages/aioredis/client.py", line 1034, in execute_command
    conn = self.connection or await pool.get_connection(command_name, **options)
  File "/root/venv/lib/python3.9/site-packages/aioredis/connection.py", line 1362, in get_connection
    await connection.connect()
  File "/root/venv/lib/python3.9/site-packages/aioredis/connection.py", line 651, in connect
    if self.is_connected:
  File "/root/venv/lib/python3.9/site-packages/aioredis/connection.py", line 641, in is_connected
    return bool(self._reader and self._writer)
AttributeError: _reader

**Comment by abrookins** [comment] 2021-05-07 13:19
Hi! What version of aioredis are you using? And, looks like Python 3.9?

**Comment by Andrew-Chen-Wang** [comment] 2021-05-08 17:19
@abrookins seems like it just *happens* if a connection is not made:
```python
async def main():
     redis = aioredis.from_url("unix://asdfhlajsdf")
     print(await redis.get("123"))

asyncio.run(main())
```
which is strange because `_reader` and `_writer` are set to `None` in `__init__`...

**Comment by fr3aker** [comment] 2021-06-24 17:29
For me this also happens when a connection should be successful. Normal TCP connections work as expected.

**Comment by abrookins** [comment] 2021-07-03 00:28
I just tested Andrew's example and using a socket like @a-pixel-on-your-screen on master -- neither gave me an AttributeError. Are you folks able to reproduce?

**Comment by Andrew-Chen-Wang** [comment] 2021-07-03 15:32
I'm still able to reproduce this on master @abrookins You have to use a unix address that is obviously wrong. Another example:

```python
import asyncio
import aioredis

async def main():
    redis = aioredis.from_url("unix://asdfhlaksdhflaksjdhflkajsdhfy")
    async with redis.client() as conn:
        print(await conn.get("123"))

asyncio.run(main())
```

<details><summary>Traceback is the same as the initial example I gave</summary>

```shell
Traceback (most recent call last):
  File "/Users/blah/main.py", line 10, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/blah/main.py", line 6, in main
    async with redis.client() as conn:
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/client.py", line 880, in initialize
    self.connection = await self.connection_pool.get_connection("_")
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 1351, in get_connection
    await connection.connect()
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 651, in connect
    if self.is_connected:
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 641, in is_connected
    return bool(self._reader and self._writer)
AttributeError: _reader
```

</details>

However, this is... somewhat resolvable? There's probably a hidden error because if you use an invalid `redis://localhost:26783` uri:

```
Traceback (most recent call last):
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 654, in connect
    await self._connect()
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 681, in _connect
    reader, writer = await asyncio.open_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1064, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 34579, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 34579)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/blah/main.py", line 10, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/blah/main.py", line 6, in main
    async with redis.client() as conn:
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/client.py", line 880, in initialize
    self.connection = await self.connection_pool.get_connection("_")
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 1351, in get_connection
    await connection.connect()
  File "/Users/blah/venv/lib/python3.9/site-packages/aioredis/connection.py", line 660, in connect
    raise ConnectionError(self._error_message(e))
aioredis.exceptions.ConnectionError: Error connecting to localhost:34579. Multiple exceptions: [Errno 61] Connect call failed ('::1', 34579, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 34579).
```

So either there's some hidden error or somehow these two classes are disconnected or implemented weirdly?

**Comment by abrookins** [comment] 2021-07-03 17:16
Interesting. I'll try your latest example - I couldn't get the _reader error, though I did get expected-looking errors. I'm on a Mac - looks like you are too, is that right?

**Comment by Andrew-Chen-Wang** [comment] 2021-07-03 17:25
yup! When you mean you got the expected-looking errors, are you referring to the second traceback I sent?

**Comment by whiskeyriver** [comment] 2021-07-06 09:20
I get this as well. In my tests I'm using redislite to launch a server, and I pull the unix socket from the resulting config.

```python
In [2]: import aioredis, redislite, redis

In [3]: server = redislite.Redis(serverconfig={})

In [4]: server_config = server.config_get()

In [5]: dsn = f"unix://{server_config['unixsocket']}"

In [6]: redis_py = redis.Redis.from_url(dsn)

In [7]: async_redis = aioredis.Redis.from_url(dsn)

In [8]: redis_py.set("key", "value")
Out[8]: True

In [9]: redis_py.get("key")
Out[9]: b'value'

In [10]: server.get("key")
Out[10]: b'value'

In [11]: await async_redis.get("key")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-5d20d11faba9> in <module>
----> 1 await async_redis.get("key")

~/z/venv/lib/python3.8/site-packages/aioredis/client.py in execute_command(self, *args, **options)
   1032         pool = self.connection_pool
   1033         command_name = args[0]
-> 1034         conn = self.connection or await pool.get_connection(command_name, **options)
   1035         try:
   1036             await conn.send_command(*args)

~/z/venv/lib/python3.8/site-packages/aioredis/connection.py in get_connection(self, command_name, *keys, **options)
   1349         try:
   1350             # ensure this connection is connected to Redis
-> 1351             await connection.connect()
   1352             # connections that the pool provides should be ready to send
   1353             # a command. if not, the connection was either returned to the

~/z/venv/lib/python3.8/site-packages/aioredis/connection.py in connect(self)
    649     async def connect(self):
    650         """Connects to the Redis server if not already connected"""
--> 651         if self.is_connected:
    652             return
    653         try:

~/z/venv/lib/python3.8/site-packages/aioredis/connection.py in is_connected(self)
    639     @property
    640     def is_connected(self):
--> 641         return bool(self._reader and self._writer)
    642 
    643     def register_connect_callback(self, callback):

AttributeError: _reader
```

Further, I can access the redislite server using `redis-cli`:
```python
In [12]: dsn
Out[12]: 'unix:///tmp/tmppvf6faxw/redis.socket'
```

```shell
$ redis-cli -s /tmp/tmppvf6faxw/redis.socket get "key"
"value"
```

Here's my installed packages:
```shell
$ pip list | grep -i redis
aioredis          2.0.0a1
redis             3.5.3
redislite         6.0.674960
types-redis       3.5.4
```

**Comment by Andrew-Chen-Wang** [comment] 2021-07-06 09:22
@whiskeyriver can you confirm if this still happens on master?

**Comment by fr3aker** [comment] 2021-07-06 09:45
I can confirm that master works for me. Connecting to a socket works as expected. Connecting to an invalid socket raises a proper exception.

**Comment by Andrew-Chen-Wang** [comment] 2021-07-06 15:56
awesome thank you @fr3aker 

@abrookins I think it's worth getting another alpha or (preferably) beta release out.

**Comment by whiskeyriver** [comment] 2021-07-06 18:24
@Andrew-Chen-Wang  - I can also confirm that this works on master.

**Comment by whiskeyriver** [comment] 2021-07-06 18:24
> @whiskeyriver can you confirm if this still happens on master?

Working for me from master.

**Comment by abrookins** [comment] 2021-07-06 18:35
The connection error is also what I saw with master, and is what I consider the "expected" error for an invalid socket.

@Andrew-Chen-Wang I agree. I'll try and get a beta release up this afternoon!

**Comment by Andrew-Chen-Wang** [comment] 2021-07-06 18:43
though I couldn't reproduce this, I'd say this issue is worth closing now as the majority of people got the correct error. I'm not sure why for me it's not working (perhaps because I have redis installed using homebrew?)

Look forward to the next release!

**Closed** 2021-07-22 00:37 UTC
Labels: bug

**Comment by a-pixel-on-your-screen** [comment] 2021-08-08 12:04
I tried the latest one on pypi rn, it worked fine. Previously ig v2 wasn't available on pypi so I used the master branch that time
